### Create the Dataset

In [26]:
import pandas as pd
import numpy as np

# Define the number of samples
num_samples = 30000

# Generate sensor data in the range [0, 100]
sensor_data = np.random.randint(0, 101, size=(num_samples, 8))

# Create a DataFrame for sensor data
sensor_df = pd.DataFrame(sensor_data, columns=['sensor1', 'sensor2', 'sensor3', 'sensor4', 'sensor5', 'sensor6', 'sensor7', 'sensor8'])

sensor_df.head()

   sensor1  sensor2  sensor3  sensor4  sensor5  sensor6  sensor7  sensor8
0       86       69       69        8       12        7       30       72
1       59       40       36       26       36       95       71       57
2       87       11       25       89       53       79       89        1
3       79       36       68       61       49       37       77       19
4       55        1       46       41       16       40       57       47

In [27]:
def calculate_throttle(sensor_data):
    avg_sensor_value = np.sqrt(np.mean(sensor_data))
    throttle = avg_sensor_value / 10  # Adjust scale if needed
    return throttle

def calculate_steering_angle(row):
    sum_first_four_sensors = row[['sensor1', 'sensor2', 'sensor3', 'sensor4']].sum()
    prod_last_four_sensors = row[['sensor5', 'sensor6', 'sensor7', 'sensor8']].prod()
    steering_angle = min(60, (prod_last_four_sensors/sum_first_four_sensors - 200) / 1000)  # Adjust scale if needed
    return steering_angle

In [28]:
# Apply functions to calculate throttle and steering angle
sensor_df['throttle'] = sensor_df.apply(calculate_throttle, axis=1)
sensor_df['steering_angle'] = sensor_df.apply(calculate_steering_angle, axis=1)

# Display the first few rows of the dataset
sensor_df.head()

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,throttle,steering_angle
0,86,69,69,8,12,7,30,72,0.664267,0.582069
1,59,40,36,26,36,95,71,57,0.724569,60.000000
2,87,11,25,89,53,79,89,1,0.736546,1.557750
3,79,36,68,61,49,37,77,19,0.729726,10.670570
4,55,1,46,41,16,40,57,47,0.615427,11.789930

In [29]:
sensor_df.to_csv("/home/ravi0531rp/Desktop/CODES/l-deep-learning/b-tf2-lp/datasets/ann_sensors.csv", index=False)